services:
  accounts:
    image: "nguyentaijs/accounts"
    container_name: "accounts_ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - backend
  loan:
    image: "nguyentaijs/loan"
    container_name: "loan_ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - backend
  cards:
    image: "nguyentaijs/cards"
    container_name: "cards_ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - backend
networks:
  backend:
    driver: "bridge"