services:
  rabbit:
    image: rabbitmq:4.0-management
    container_name: "rabbitmq_ms"
    ports:
      - "5671:5671"
      - "15671:15671"
    networks:
      - backend
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 3

  configserver:
    image: "nguyentaijs/configserver"
    container_name: "configserver_ms"
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - backend
    healthcheck:
      #      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8071/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      rabbit:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "configserver"
      SPRING_RABBITMQ_HOST: "rabbit"
  accounts:
    image: "nguyentaijs/accounts"
    container_name: "accounts_ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - backend
    environment:
      SPRING_CONFIG_IMPORT: "http://configserver:8071/"
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_APPLICATION_NAME: "accounts"
    depends_on:
      configserver:
        condition: service_healthy
  loan:
    image: "nguyentaijs/loan"
    container_name: "loan_ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - backend
    environment:
      SPRING_CONFIG_IMPORT: "http://configserver:8071/"
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_APPLICATION_NAME: "loan"
    depends_on:
      configserver:
        condition: service_healthy
  cards:
    image: "nguyentaijs/cards"
    container_name: "cards_ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - backend
    environment:
      SPRING_CONFIG_IMPORT: "http://configserver:8071/"
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_APPLICATION_NAME: "cards"
    depends_on:
      configserver:
        condition: service_healthy
networks:
  backend:
    driver: "bridge"